apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-rwx
  namespace: andre-llama-cpp
  labels:
    app: llama-cpp
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 30Gi