apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: andre-llama-cpp
  labels:
    app: llama-cpp
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  # Uncomment and specify storageClassName if you have a specific storage class
  # storageClassName: your-storage-class